/* He creado una db llamada ironhack para este ejercicio */
CREATE TABLE `requests` (
  `id` int NOT NULL AUTO_INCREMENT,
  `unique_key` text,
  `created_date` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `agency` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `agency_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `complaint_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `descriptor` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `incident_zip` text,
  `intersection_street_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `intersection_street_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `address_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `city` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `facility_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `status` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `resolution_description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `resolution_action_updated_date` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `community_board` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `borough` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `x_coordinate_state_plane` text,
  `y_coordinate_state_plane` text,
  `open_data_channel_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `park_facility_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `park_borough` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `latitude` text,
  `longitude` text,
  `location/latitude` text,
  `location/longitude` text,
  `location/human_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `:@computed_region_efsh_h5xi` text,
  `:@computed_region_f5dn_yrer` text,
  `:@computed_region_yeji_bk3q` text,
  `:@computed_region_92fq_4b7q` text,
  `:@computed_region_sbqj_enih` text,
  `:@computed_region_7mpf_4k6g` text,
  `incident_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `street_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `cross_street_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `cross_street_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `bbl` text,
  `location_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `landmark` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `vehicle_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `closed_date` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `due_date` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `taxi_company_borough` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `taxi_pick_up_location` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `bridge_highway_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `bridge_highway_direction` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `road_ramp` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `bridge_highway_segment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  PRIMARY KEY (`id`)
)